apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - name: webapp2
        image: ngtrainings/springboot-helloworld-master:v1
        ports:
        - containerPort: 2020
